- name: Setup Workstation
  hosts: local
  vars_prompt:
    - name: hostname
      prompt: Hostname
      private: false
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: Install packages
      become: true
      ansible.builtin.dnf5:
        name:

          # system
          - "fido2-tools"
          - "gnome-keyring"
          - "greetd"
          - "pam-u2f"
          - "pamu2fcfg"
          - "udiskie"
          - "xdg-desktop-portal"
          - "xdg-desktop-portal-gnome"
          - "xdg-desktop-portal-gtk"
          - "xdg-desktop-portal-wlr"
          - "xdg-user-dirs"

          # niri
          - "adw-gtk3-theme"
          - "niri"
          - "noctalia"
          - "noctalia-greeter"

          # cli
          - "atuin"
          - "bat"
          - "btop"
          - "chezmoi"
          - "cowsay"
          - "direnv"
          - "eza"
          - "fish"
          - "flatpak"
          - "fortune-mod"
          - "lolcat"
          - "mise"
          - "scrcpy"
          - "tmux"
          - "uv"
          - "yazi"
          - "zoxide"

          # dev
          - "gh"
          - "ghostty"
          - "git"
          - "git-delta"
          - "git-lfs"
          - "lazygit"
          - "neovim"

          # apps
          - "brave-browser"
          - "fcitx5"
          - "fcitx5-rime"
          - "kdeconnectd"
          - "nemo"
          - "nemo-fileroller"
          - "nwg-look"
          - "qalculate-gtk"
          - "qimgv"
          - "signal-desktop"
          - "syncthing"

          # fonts
          - "google-noto-color-emoji-fonts"
          - "google-noto-sans-cjk-fonts"
          - "google-noto-sans-fonts"
          - "google-noto-serif-cjk-fonts"
          - "google-noto-serif-fonts"
          - "jetbrains-mono-fonts-all"
          - "nerdfontssymbolsonly-nerd-fonts"
          - "victor-mono-fonts"

        state: "latest"

    - name: Create default directories
      ansible.builtin.command: xdg-user-dirs-update
      register: command_output
      changed_when: command_output.rc != 0

    - name: Create Anurati font directory
      ansible.builtin.file:
        path: /home/{{ ansible_facts['user_id'] }}/.local/share/fonts/Anurati
        state: directory
        mode: "0755"

    - name: Install Anurati font
      ansible.builtin.unarchive:
        src: ./Anurati-Regular.otf.zip
        dest: /home/{{ ansible_facts['user_id'] }}/.local/share/fonts/Anurati

    - name: Enable noctalia-greeter in greetd
      ansible.builtin.lineinfile:
        path: /etc/greetd/config.toml
        regexp: '^command\s*='
        line: 'command = "/usr/bin/noctalia-greeter-session"'
        state: present
        backup: true
        mode: '0644'
