---
- name: Setup Workstation
  hosts: local
  vars_prompt:
    - name: hostname
      prompt: Hostname
      private: false
  tasks:
    - name: Set hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: Ensure "max_parallel_downloads=10" is in section "[main]" in dnf.conf
      become: true
      community.general.ini_file:
        path: /etc/dnf/dnf.conf
        section: main
        option: max_parallel_downloads
        value: 10
        mode: "0644"
        backup: true

    - name: Ensure "defaultyes=True" is in section "[main]" in dnf.conf
      become: true
      community.general.ini_file:
        path: /etc/dnf/dnf.conf
        section: main
        option: defaultyes
        value: "True"
        mode: "0644"
        backup: true

    - name: Enable the RPM Fusion free repository
      become: true
      ansible.builtin.dnf:
        name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_version'] }}.noarch.rpm"
        disable_gpg_check: true
        state: present

    - name: Enable the RPM Fusion nonfree repository
      become: true
      ansible.builtin.dnf:
        name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_version'] }}.noarch.rpm"
        disable_gpg_check: true
        state: present

    - name: Enable brave-browser repository
      become: true
      ansible.builtin.command:
        argv:
          - dnf
          - config-manager
          - addrepo
          - --from-repofile=https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      register: command_output
      changed_when: command_output.rc != 0

    - name: Enable terra repository
      become: true
      ansible.builtin.command:
        argv:
          - dnf
          - install
          - -y
          - --nogpgcheck
          - --repofrompath
          - terra,https://repos.fyralabs.com/terra{{ ansible_facts['distribution_version'] }}
          - terra-release
          - terra-gpg-keys
      register: command_output
      changed_when: command_output.rc != 0

    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          # system
          - "fido2-tools"
          - "gnome-keyring"
          - "greetd"
          - "libappindicator-gtk3"
          - "pam-u2f"
          - "pamu2fcfg"
          - "udiskie"
          - "xdg-desktop-portal"
          - "xdg-desktop-portal-gnome"
          - "xdg-desktop-portal-gtk"
          - "xdg-desktop-portal-wlr"
          - "xdg-user-dirs"

          # niri
          - "adw-gtk3-theme"
          - "bibata-cursor-theme"
          - "niri"
          - "noctalia"
          - "noctalia-greeter"
          - "papirus-icon-theme"

          # cli
          - "atuin"
          - "bat"
          - "btop"
          - "chafa"
          - "chezmoi"
          - "cowsay"
          - "direnv"
          - "eza"
          - "fastfetch"
          - "fd-find"
          - "fish"
          - "flatpak"
          - "fortune-mod"
          - "fzf"
          - "jq"
          - "lolcat"
          - "mise"
          - "playerctl"
          - "ripgrep"
          - "scrcpy"
          - "starship"
          - "tectonic"
          - "tmux"
          - "uv"
          - "yazi"
          - "zoxide"

          # dev
          - "gh"
          - "ghostty"
          - "git"
          - "git-delta"
          - "git-lfs"
          - "lazygit"
          - "neovim"

          # apps
          - "ImageMagick"
          - "brave-browser"
          - "fcitx5"
          - "fcitx5-rime"
          - "kdeconnectd"
          - "libreoffice"
          - "nemo"
          - "nemo-fileroller"
          - "nwg-look"
          - "qalculate-gtk"
          - "qimgv"
          - "satty"
          - "signal-desktop"
          - "syncthing"

          # fonts
          - "google-noto-color-emoji-fonts"
          - "google-noto-sans-cjk-fonts"
          - "google-noto-sans-fonts"
          - "google-noto-serif-cjk-fonts"
          - "google-noto-serif-fonts"
          - "jetbrains-mono-fonts-all"
          - "nerdfontssymbolsonly-nerd-fonts"
          - "victor-mono-fonts"

    - name: Create default directories
      ansible.builtin.command: xdg-user-dirs-update
      register: command_output
      changed_when: command_output.rc != 0

    - name: Create Anurati font directory
      ansible.builtin.file:
        path: /home/{{ ansible_facts['user_id'] }}/.local/share/fonts/Anurati
        state: directory
        mode: "0755"

    - name: Install Anurati font
      ansible.builtin.unarchive:
        src: ./Anurati-Regular.otf.zip
        dest: /home/{{ ansible_facts['user_id'] }}/.local/share/fonts/Anurati

    - name: Enable noctalia-greeter in greetd
      become: true
      ansible.builtin.lineinfile:
        path: /etc/greetd/config.toml
        regexp: "^command\\s*="
        line: 'command = "/usr/bin/noctalia-greeter-session"'
        state: present
        backup: true
        mode: "0644"

    - name: Enable greetd service
      become: true
      ansible.builtin.systemd_service:
        name: greetd
        enabled: true
        state: started
