- name: Create Anurati font directory
  ansible.builtin.file:
    path: /home/{{ ansible_facts['user_id'] }}/.local/share/fonts/Anurati
    state: directory
    mode: "0755"

- name: Install Anurati font
  ansible.builtin.unarchive:
    src: ./Anurati-Regular.otf.zip
    dest: /home/{{ ansible_facts['user_id'] }}/.local/share/fonts/Anurati

- name: Create default directories
  ansible.builtin.command: xdg-user-dirs-update
  register: user_command_output
  changed_when: user_command_output.rc != 0

- name: Set nemo default terminal to ghostty
  community.general.dconf:
    key: /org/cinnamon/desktop/applications/terminal/exec/
    value: ghostty
    state: present

- name: Set meno default terminal exec args
  community.general.dconf:
    key: /org/cinnamon/desktop/applications/terminal/exec-arg/
    value: "+new-window --working-directory"
