- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Create Anurati font directory
  ansible.builtin.file:
    path: /home/{{ ansible_facts['user_id'] }}/.local/share/fonts/Anurati
    state: directory
    mode: "0755"

- name: Install Anurati font
  ansible.builtin.unarchive:
    src: ./Anurati-Regular.otf.zip
    dest: /home/{{ ansible_facts['user_id'] }}/.local/share/fonts/Anurati

- name: Create default directories
  ansible.builtin.command: xdg-user-dirs-update
  register: user_command_output
  changed_when: user_command_output.rc != 0
