- name: Install packages
  become: true
  ansible.builtin.package:
    name:

      # system
      - "fido2-tools"
      - "fuse"
      - "fuse-libs"
      - "gnome-keyring"
      - "greetd"
      - "libappindicator-gtk3"
      - "pam-u2f"
      - "pamu2fcfg"
      - "python3-pillow"
      - "python3-psutil"
      - "udiskie"
      - "xdg-desktop-portal"
      - "xdg-desktop-portal-gnome"
      - "xdg-desktop-portal-gtk"
      - "xdg-desktop-portal-wlr"
      - "xdg-user-dirs"

      # niri
      - "adw-gtk3-theme"
      - "bibata-cursor-theme"
      - "niri"
      - "noctalia"
      - "noctalia-greeter"
      - "papirus-icon-theme"

      # cli
      - "bat"
      - "btop"
      - "chafa"
      - "chezmoi"
      - "cowsay"
      - "direnv"
      - "eza"
      - "fastfetch"
      - "fd-find"
      - "fish"
      - "flatpak"
      - "fortune-mod"
      - "fzf"
      - "jq"
      - "tailscale"
      - "lolcat"
      - "mise"
      - "playerctl"
      - "ripgrep"
      - "scrcpy"
      - "starship"
      - "tectonic"
      - "tmux"
      - "uv"
      - "yazi"
      - "socat"
      - "yq"
      - "zoxide"

      # dev
      - "gh"
      - "ghostty"
      - "git"
      - "git-delta"
      - "git-lfs"
      - "lazygit"
      - "neovim"

      # apps
      - "ImageMagick"
      - "brave-browser"
      - "fcitx5"
      - "fcitx5-rime"
      - "kdeconnectd"
      - "libreoffice"
      - "mpv"
      - "nemo"
      - "nemo-fileroller"
      - "nwg-look"
      - "qalculate-gtk"
      - "qimgv"
      - "satty"
      - "seahorse"
      - "signal-desktop"
      - "syncthing"

      # fonts
      - "google-noto-color-emoji-fonts"
      - "google-noto-sans-cjk-fonts"
      - "google-noto-sans-fonts"
      - "google-noto-serif-cjk-fonts"
      - "google-noto-serif-fonts"
      - "jetbrains-mono-fonts-all"
      - "nerdfontssymbolsonly-nerd-fonts"
      - "victor-mono-fonts"
